fix: remove buggy macAdress() code from analytics.js
I noticed that analytics events are not sent from my machine, an Ubuntu
17.04 VM. Debugging the issue showed that macAdress() threw an
TypeError: Cannot read property 'indexOf' of undefined (ass curr, the
second param of reduce() callback is undefined)
Discussing it with @adrukh we decided that it's better to remove the
call to macAdress() and always use uuid.v4() instead of fixing the buggy
code.